# Generated by Django 4.0.1 on 2022-01-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimestampedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_time_now', models.CharField(max_length=255)),
                ('stamp_uuid_now', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'TimestampedModel',
            },
        ),
    ]
